name: homenetwork_tv
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  http: ^1.2.0
  path_provider: ^2.1.0
  archive: ^3.6.0
  idb_shim: ^2.2.0
  video_player: ^2.8.2
  shared_preferences: ^2.2.2
  media_kit: ^1.1.0
  media_kit_video: ^1.1.0
  media_kit_libs_video: ^1.0.7
  webview_flutter: ^4.0.7
  webview_flutter_android: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
